pluginManagement {
    includeBuild("build-logic")
    repositories {
        mavenCentral()
        gradlePluginPortal()
        google()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
        
        maven { 
            url 'https://jitpack.io' 
            // 👇👇👇 关键修改：黑名单机制 👇👇👇
            content {
                // 明确告诉 Gradle：只要是 io.github.dokar3 开头的库（即 QuickJS），
                // 绝对不要来 JitPack 找！(防止触发 401 错误)
                excludeGroup 'io.github.dokar3'
            }
        }
    }

    versionCatalogs {
        libs {
            from(files("./libs.versions.toml"))
        }
    }
}

rootProject.name = "TTS Server"
include ':app'
include ':lib-common'
include ':lib-compose'
include ':lib-database'
include ':lib-tts'
include ':lib-script'
include ':lib-server'
