      - name: Init Signature
        run: |
          touch local.properties
          echo ALIAS_NAME='${{ secrets.ALIAS_NAME }}' >> local.properties
          echo ALIAS_PASSWORD='${{ secrets.ALIAS_PASSWORD }}' >> local.properties
          echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> local.properties
          # 使用绝对路径指向解压后的 jks
          echo KEY_PATH='${{ github.workspace }}/app/key.jks' >> local.properties
          
          # 从 Secrets 读取 Base64 并解码到指定位置
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > ${{ github.workspace }}/app/key.jks

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemble${{ env.product }}release --build-cache --parallel --daemon --warning-mode all

      - name: Set Version Name
        run: |
          echo "ver_name=$(grep -m 1 'versionName' ${{ env.outputs_dir }}/apk/${{ env.product }}/release/output-metadata.json | cut -d\" -f4)" >> $GITHUB_ENV

      - name: Upload APK To Artifact
        uses: actions/upload-artifact@v4
        with:
          # 下载时的压缩包名称
          name: "TTS-Server_${{ env.product }}_${{ env.ver_name }}"
          # 具体的 APK 文件路径
          path: ${{ env.outputs_dir }}/apk/${{ env.product }}/release/*.apk
